= Digital Circuits

=== Background

VHDL:: Very High Speed Integrated Circuit (VHSIC) Hardware Description Language (HDL), which is a programming language used to describe a logic circuit by function, data flow behavior, or structure.
- superset of ADA programming language
- VHDL is a highly concurrent language, built upon an *event-based timing model*.
- VHDL is used to model digital designs
- Both *.vhdl* and *.vhd* extensions are used for VHDL source files, while *.v* is used for Verilog.
- Fast as no intermediate code is generated. Directly from VHDL -> machine code
- VHDL is frequently used for two different goals: *simulation* of electronic designs and *synthesis* of such designs.
- *Synthesis* is a process where a VHDL is compiled and mapped into an implementation technology such as an FPGA or an ASIC (Application specific integrated circuit).
- RTL or Data Flow Design, programs are represented as Directed Graphs

RTL:: Register transfer level design abstraction which models a synchronous digital circuit in terms of the flow of digital signals (data) between hardware registers, and the logical operations performed on those signals.
- Approach to digital design  or *dataflow* design. This is the method currently used for the design of complex logic circuits such as microprocessors.

https://ghdl.readthedocs.io/en/latest/[GHDL]:: VHDL Compile
- is not a synthesis tool: you cannot create a netlist with GHDL (yet). *A netlist* is a description of the connectivity of an electronic circuit. In its simplest form, a netlist consists of a list of the electronic components in a circuit and a list of the nodes they are connected to. A network (net) is a collection of two or more interconnected components.
- GHDL is an open-source simulator for the VHDL language. GHDL allows you to compile and execute your VHDL code directly in your PC.

GtkWave::  graphical waveform viewer

IP Core:: https://en.wikipedia.org/wiki/Semiconductor_intellectual_property_core

=== A quickstart to GHDL and GTKWave

0. It is assumed that the design and testbench are created at this point.
1. Launch a console window
2. Navigate to the directory containing the design and testbench
3. Compile and simulate the design with GHDL
----
ghdl -s some_design.vhd testbench.vhd               to check the syntax. This step step is optional.
ghdl -a some_design.vhd testbench.vhd               to analyze the design.
ghdl -e testbench_entity_name                       to build an executable for the testbench.
ghdl -r testbench_entity_name --vcd=file_name.vcd   to simulate the design and dump the waveform to a file.
----

====
----
ghdl -r options
--stop-time=10ns/ps
--disp-time
--wave=filename.ghw / --vcd=filename.vcd
----
====


4. Examine the waveform with GTKWave
----
gtkwave file_name.vcd                               to launch GTKWave
ghdl --remove && ghdl --clean                       to clean library and other created files
----

'''
[To go through]
====
.Some References List
. [] http://www.ece.ubc.ca/~edc/379/lectures/
. [*] https://github.com/vagizduseev/DresdenVHDL
. [X] https://github.com/DheerendraRathor/vhdl
. https://www.seas.upenn.edu/~ese171/vhdl/vhdl_primer.html#_Toc526061365
. [ ] http://www.vhdl.renerta.com/mobile/index.html
. http://web.engr.oregonstate.edu/~traylor/ece474/vhdl_lectures/component_instantiaton.pdf
. http://vhdlguru.blogspot.com/
====  
